baseURL = "https://rivik.github.io/"
languageCode = "en-us"
title = "Ilya Rusalowski"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[permalinks]
  posts = "/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  env = "production"
  defaultTheme = "auto"
  mainSections = ["posts"]
  ShowCanonicalLink = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  ShowRssButtonInSectionTermList = true

[params.homeInfoParams]
  Title = "Ilya Rusalowski"
  Content = "Personal hub: originals + reposts from my projects"

[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 10

[[menu.main]]
  identifier = "posts"
  name = "posts"
  url = "/posts/"
  weight = 20

[[menu.main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
  weight = 30

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
